# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20171023_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNo', models.IntegerField()),
                ('pwd', models.CharField(max_length=16)),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userAge', models.IntegerField()),
                ('userBirthday', models.DateField()),
                ('userProfession', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
