# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20171113_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=10)),
                ('devotionTime', models.DateField()),
                ('devoter', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('link', models.FileField(upload_to='')),
            ],
        ),
    ]
