# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.URLField(),
        ),
    ]
