# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20171121_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='D:/system/mysystem/learn/knowledge/file/'),
        ),
    ]
