# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20171121_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='modelNo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='file/'),
        ),
    ]
