# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20171122_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=10)),
                ('chartNo', models.CharField(default=0, max_length=20)),
                ('devotionTime', models.DateField()),
                ('devoter', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
                ('link', models.ImageField(upload_to='chart/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.FileField(upload_to='data/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='file/%Y/%m/%d/'),
        ),
    ]
